### ISSUE TITLE
Unexpected input(s) 'displayProgress', valid inputs are ['accessToken', 'pattern', 'file', 'destination']

### ISSUE THREAD

**Issue by D3vil0p3r** [whalemare/action-dropbox#200]
From `actions.yml` I see that there is `displayProgress` input that I can use. When I use your GitHub Actions on my file like:
```
      - name: Deploy to Dropbox
        uses: whalemare/action-dropbox@v1.0.0
        with:
          accessToken: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          destination: "/"
          file: "$HOME/Athena-Out/athena-${{env.ISO_VERSION}}-${{env.ISO_ARCHITECTURE}}.iso"
          displayProgress: true
```
during the action process I get the following error:
```
Warning: Unexpected input(s) 'displayProgress', valid inputs are ['accessToken', 'pattern', 'file', 'destination']
Run whalemare/action-dropbox@v1.0.0
  with:
    accessToken: ***
    destination: /
    file: $HOME/Athena-Out/athena-[2](https://github.com/Athena-OS/athena-iso/actions/runs/5112239121/jobs/9190054969#step:7:2)02[3](https://github.com/Athena-OS/athena-iso/actions/runs/5112239121/jobs/9190054969#step:7:3).06.01-x86_6[4](https://github.com/Athena-OS/athena-iso/actions/runs/5112239121/jobs/9190054969#step:7:4).iso
    displayProgress: true
    pattern: default value if applicable
  env:
    ATHENA_VERSION: unstable
    ISO_VERSION: 2023.06.01
    ISO_ARCHITECTURE: x86_64
/usr/bin/docker exec  aa[5](https://github.com/Athena-OS/athena-iso/actions/runs/5112239121/jobs/9190054969#step:7:5)7fc89101bfac8[6](https://github.com/Athena-OS/athena-iso/actions/runs/5112239121/jobs/9190054969#step:7:6)9b0[7](https://github.com/Athena-OS/athena-iso/actions/runs/5112239121/jobs/9190054969#step:7:7)412ebb5f522de067ae010dfd35dbe556dec[8](https://github.com/Athena-OS/athena-iso/actions/runs/5112239121/jobs/9190054969#step:7:8)7f7d105 sh -c "cat /etc/*release | grep ^ID"
Error: Cannot find module 'fs/promises'
Require stack:
- /__w/_actions/whalemare/action-dropbox/v1.0.0/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:1[9](https://github.com/Athena-OS/athena-iso/actions/runs/5112239121/jobs/9190054969#step:7:9))
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.9225 (/__w/_actions/whalemare/action-dropbox/v1.0.0/webpack:/dropbox-uploader/external "fs/promises":1:1)
    at __webpack_require__ (/__w/_actions/whalemare/action-dropbox/v1.0.0/webpack:/dropbox-uploader/webpack/bootstrap:20:1)
    at Object.3[10](https://github.com/Athena-OS/athena-iso/actions/runs/5112239121/jobs/9190054969#step:7:10)9 (/__w/_actions/whalemare/action-dropbox/v1.0.0/webpack:/dropbox-uploader/lib/main.js:31:1)
    at __webpack_require__ (/__w/_actions/whalemare/action-dropbox/v1.0.0/webpack:/dropbox-uploader/webpack/bootstrap:20:1)
    at /__w/_actions/whalemare/action-dropbox/v1.0.0/webpack:/dropbox-uploader/webpack/startup:4:1
    at Object.<anonymous> (/__w/_actions/whalemare/action-dropbox/v1.0.0/dist/index.js:14853:[12](https://github.com/Athena-OS/athena-iso/actions/runs/5112239121/jobs/9190054969#step:7:12))
```

**Comment by D3vil0p3r** [comment]
Even if I remove that input, I see that the main issue is caused by `Error: Cannot find module 'fs/promises'`. How can I solve this?
